# Generated by Django 4.2.5 on 2023-09-30 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, default='')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='assets/avatars')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='cover_image')),
                ('archived', models.ManyToManyField(blank=True, related_name='Archived', to='App.chatroom')),
                ('favourite', models.ManyToManyField(blank=True, related_name='favourite', to='App.chatroom')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
